# on:
#   push:
#     branches:
#       - main
# name: 🚀 Deploy website on push
# jobs:
#   web-deploy:
#     name: 🎉 Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: 🚚 Get latest code
#         uses: actions/checkout@v2

#       - name: 📂 Sync files
#         uses: SamKirkland/FTP-Deploy-Action@4.1.0
#         with:
#           server: business100.web-hosting.com
#           username: ${{secrets.username}}
#           password: ${{secrets.password}}
#           Port: 21
# security: strict

on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: Penguibird/FTP-Deploy-Action@4.2.0
        with:
          server: business62.web-hosting.com
          protocol: ftps
          username: ${{secrets.username}}
          password: ${{secrets.password}}

          # Optional, default is 21
